### ISSUE TITLE
upload方法配置拦截器报错

### ISSUE THREAD

**Issue by africa1207** [lei-mu/luch-request#10]
`// request.js 拦截器封装
import Request from 'luch-request'
import {baseURL} from "@/config";

const service = new Request({
    baseURL,
    method: 'POST',
    timeout: 12000 // request timeout
});

service.interceptors.request.use(
    config => {
        // 拦截器header加参
        config.header = {
            ...config.header,
        }
        return config
    },
    error => {
        return Promise.reject(error)
    }
)

service.interceptors.response.use(
    response => {
        const res = response.data
        if (res.returnCode !== 1) {
            return Promise.reject(new Error(res.returnMsg || 'Error'))
        }
        return res
    },
    error => {
        uni.showToast({
            title: error.msg || 'Server Error',
            icon: "none",
            duration: 2 * 1000
        })
        return Promise.reject(error)
    }
)
export default service`

`// api.js
import http from '../common/js/request'
export const loginWeixin = ({code,encryptedData,iv})=>{
    return http.request({
        url: '/user/loginWeixin',
        data:{code,encryptedData,iv}
    })
}
export const uploadFile = ({filePath})=>{
    return http.upload('/file/uploadFile',{
        name:'file',
        filePath,
    })
}`
普通的request请求 loginWeixin没问题，但是uploadFile请求则直接进入响应拦截器的catch里面error了。。。

**Comment by lei-mu** [comment]
终端是啥？报错是啥，你说清楚

**Comment by africa1207** [comment]
![image](https://user-images.githubusercontent.com/21698755/92362144-23cc6000-f122-11ea-86c8-e1398285399b.png)

**Comment by lei-mu** [comment]
我看下你调用uploadFile 代码

**Comment by africa1207** [comment]
我使用的中关村的接口 
接口：http://my.zol.com.cn/index.php?c=Ajax_User&a=uploadImg
请求方式：POST
表单name：myPhoto
![image](https://user-images.githubusercontent.com/21698755/92362842-2bd8cf80-f123-11ea-90f5-164f085c00a3.png)

**Comment by lei-mu** [comment]
后边把catch 写上，打印一下

**Comment by africa1207** [comment]
加个.catch(e=>{})后正常了，-_-||

**Comment by lei-mu** [comment]
出现这个一般就是说promise出现了一个错误，你没有捕获,写个catch就好了
