### ISSUE TITLE
在请求之前拦截中执行 return Promise.reject(config) 取消请求，network中没有，但该请求最终还是执行了then逻辑

### ISSUE THREAD

**Issue by ren2436** [lei-mu/luch-request#100]
非常感谢作者的辛苦付出，目前有一个问题不知如何解决
如题，取消请求后，network中没有是正常的，但该请求最后执行了then的逻辑是错误的，应该执行 catch
这个问题怎么修复
当前运行环境为 微信小程序

**Comment by lei-mu** [comment]
复现不了，看一下响应拦截器处理。

**Comment by ren2436** [comment]
的确是，昨天在回去的路上突然想起来，取消的请求会执行相应拦截器的失败函数，之前在里边只做了个return处理，并没有 return Promise.reject，所以导致走了then函数，抱歉了，是我的疏忽
