### ISSUE TITLE
支持http2请求吗，

### ISSUE THREAD

**Issue by pigping88** [lei-mu/luch-request#113]
支持http2请求吗，目前服务端nginx开启了http2，浏览访问看了下，采用了http2协议，你这个如果拿来做微信小程序，是否支持开启http2，微信有个自带的属性，wx.request()，有个enable Http2属性是否开启http2协议，你这个能否对接http2

**Comment by lei-mu** [comment]
会尽快支持

**Comment by pigping88** [comment]
我自己改了源码，微信小程序是可以了，app，目前好像不行，因为微信小程序自己处理过网络请求，app，默认是没有http2支持，估计要换webview，手机默认的可能不支持，目前华为的是不行，不知道腾讯x5是否支持app的http2请求

**Comment by lei-mu** [comment]
改源码，后期升级可能无法使用。使用最新版本就可以了。

uni http2 支持还是得看uni. 
https://ask.dcloud.net.cn/question/167606
https://ask.dcloud.net.cn/question/80958
