### ISSUE TITLE
安卓请求，nginx 配置http无法重定向https

### ISSUE THREAD

**Issue by mmdlsu** [lei-mu/luch-request#116]
nginx配置
`server {` 
    `listen 80;`
    `server_name xxx.xxxxxx.xx;`
    `return 307 https://$server_name$request_uri;`
`}`

使用postman发送post请求，nginx日志正常是2条请求
![image](https://github.com/lei-mu/luch-request/assets/57515771/62e1d5db-6045-487f-892c-e56885ed678d)
APP却只有一条
![image](https://github.com/lei-mu/luch-request/assets/57515771/b9363c31-9416-4cea-a438-d420748356ee)

**Comment by lei-mu** [comment]
用uni.request 测试下，不清楚这种情况

````
    #SSL-START SSL相关配置，请勿删除或修改下一行带注释的404规则
    #error_page 404/404.html;
    #HTTP_TO_HTTPS_START
    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    } 
````

**Comment by mmdlsu** [comment]
uni.request也是这种情况
