### ISSUE TITLE
微信小程序，不支持吗？无法设置baseURL ，h5端能发请求

### ISSUE THREAD

**Issue by githublmy** [lei-mu/luch-request#119]
![image](https://github.com/lei-mu/luch-request/assets/35590555/e2f3d994-8752-44d2-a514-25d098194bcf)

**Comment by githublmy** [comment]
![image](https://github.com/lei-mu/luch-request/assets/35590555/941c8f01-fa49-4787-a264-45d132c899cf)
这个是 网页，上面是小程序模拟器

**Comment by lei-mu** [comment]
我看你设置baseURL 的代码

**Comment by githublmy** [comment]
![image](https://github.com/lei-mu/luch-request/assets/35590555/3408e5a4-6dcc-40da-98bd-516b640caa86)

都按照文档来的，

**Comment by githublmy** [comment]
这里都没请求，但是网页可以，以前用uview2 也是h5可以，小程序用不了，不知道其他人有没有同样的

**Comment by lei-mu** [comment]
小程序支持的。
你这个baseRUL 打印出来是个什么
需要更多信息。可以加qq 发更多关键代码、和调试信息

**Comment by githublmy** [comment]
uview官网的写法小程序不行，用git上示例可以了

**Comment by lei-mu** [comment]
是不是setConfig 的执行时机太后了，导致开始请求了，还没设置config 

在setConfig custom 多设置几个值 试试可以不

在请求完成 打印  uni.$u.config

debugger 看一下

**Comment by githublmy** [comment]
![image](https://github.com/lei-mu/luch-request/assets/35590555/8809a21d-166a-4930-8c44-b8cc9463d765)

uview官网写法挂载uni.$u.http，这个在小程序挂载不上，应该是uview写法问题，跟插件无关 ，用示例写法  const  http= new Request() 可以请求，
下面这种可以用
![image](https://github.com/lei-mu/luch-request/assets/35590555/57f34014-61d9-4b67-b628-9925a8b4e4e3)
