### ISSUE TITLE
我有一个接口对接了chatgpt，数据是流式返回的，如何能流式的取数据？

### ISSUE THREAD

**Issue by 2424004764** [lei-mu/luch-request#120]
我需要用post方式先发送一些数据给这个chatgpt的接口，然后接口才能返回流式内容，我要怎么对接才能流式的取数据呢？

**Comment by lei-mu** [comment]
都有什么端

**Comment by 2424004764** [comment]
目前只在小程序端 @lei-mu

**Comment by lei-mu** [comment]
可以试试 [enableChunked: true 方案](https://blog.csdn.net/u012632466/article/details/130810599)。
注意插件必须是最新版本，否则不支持这个配置

**Comment by 2424004764** [comment]
有用
