### ISSUE TITLE
没有 PATCH请求方式吗 ？

### ISSUE THREAD

**Issue by dong-lufei** [lei-mu/luch-request#121]
我这里的别人提供的接口要求PATCH ，不是put

**Comment by dong-lufei** [comment]
@lei-mu 干嘛关闭，是你这做不了patch方法，还是你的依赖就不支持patch请求？我这现在还要多写个后端做请求转发...

**Comment by lei-mu** [comment]
看文档   关于问问题  如何问问题    
你这样问，我只能说uni不支持
