### ISSUE TITLE
node版本限制应是大于等于16，而非16吧，否则node18会无法安装

### ISSUE THREAD

**Issue by seepine** [lei-mu/luch-request#123]

**Comment by lei-mu** [comment]
目前应该不影响插件运行环境，也不影响插件的install
下版本会修改
----

**Comment by lei-mu** [comment]
engines只是起一个说明提示的作用，即使用户安装的版本不符合要求，也不影响依赖包的安装。本地也测试了不影响。

已经发布了 3.1.1 版本解决这个问题，重新安装一下

**Comment by seepine** [comment]
> engines只是起一个说明提示的作用，即使用户安装的版本不符合要求，也不影响依赖包的安装。本地也测试了不影响。
> 
> 已经发布了 3.1.1 版本解决这个问题，重新安装一下

实际情况是我安装依赖时被阻止了无法进行，后来我加了 `yarn --ignore-engines` 忽略才能安装，十分感谢
