### ISSUE TITLE
请问有没有遇到过这个问题，new这个类，直接使用request.delete会说is not a function?如果是request.get或者post或者put都正常，唯独delete有问题

### ISSUE THREAD

**Issue by li460930736** [lei-mu/luch-request#126]
import Request from 'luch-request';
const  request = new Request();
request.delete(...);

浏览器f12会报错
request.delete is not a function

**Comment by lei-mu** [comment]
h5 无法复现。提供可复现的demo

**Comment by li460930736** [comment]
> h5 无法复现。提供可复现的demo

估计是前人的依赖引起的，测试环境才有这个问题，正式没有
