### ISSUE TITLE
validateStatus设置无效

### ISSUE THREAD

**Issue by kevin2653** [lei-mu/luch-request#127]
const baseConfig = {
    baseURL: "http://localhost:8000",
    timeout: config.timeout,
    validateStatus: (statusCode) => { // statusCode 必存在。此处示例为全局默认配置
        console.log('kevin')
        console.log(statusCode);
        // statusCode >= 200 && statusCode < 300
        return true
    }
};

request.interceptors.response.use(
    (response) => {
        console.log('kevin')
        // let code = response.data.code;
        // if (code != 100) return Promise.reject(response.data);
        // return response.data.data;
        return response.data;
    },
    (err) => {
        console.log(err);
        console.log('kevin')
       //问题在这里：如果没有手动调用，baseConfig里面validateStatus未调用，只有在此处调用，但是通过err获取不到statusCode，请问如果处理 
        err.config.validateStatus()
}）

**Comment by kevin2653** [comment]
补充一下：以上是在服务器不同的情况时候测得，关掉服务器之后就不能调用

**Comment by lei-mu** [comment]
```` js
const api = new Request({
	validateStatus () {
		return true
	}
})

api.get(' http://localhost:15840/api/error').then(res => {
	console.log(res);
}).catch(err => {
	console.log(err);
})
````
如果api 响应了，不论statusCode 是多少，都会进入then.
如果 api 没有响应，比如一个不存在的 域名，这时候没有statusCode,会进入 catch.
没理解你的意思

**Comment by kevin2653** [comment]
理解了，谢谢
