### ISSUE TITLE
请问怎样取消正在请求中的请求？

### ISSUE THREAD

**Issue by jarrelljiang** [lei-mu/luch-request#13]
有一个场景是频繁请求同一个接口，假如前一次请求还没有完成响应，就取消前一次请求，因为假如前一次请求比当前这一次请求响应慢些的话，前一次的响应数据会覆盖当前请求的响应数据

**Comment by jarrelljiang** [comment]
> 有一个场景是频繁请求同一个接口，假如前一次请求还没有完成响应，就取消前一次请求，因为假如前一次请求比当前这一次请求响应慢些的话，前一次的响应数据会覆盖当前请求的响应数据

**Comment by jarrelljiang** [comment]
> 有一个场景是频繁请求同一个接口，假如前一次请求还没有完成响应，就取消前一次请求，因为假如前一次请求比当前这一次请求响应慢些的话，前一次的响应数据会覆盖当前请求的响应数据

**Comment by jarrelljiang** [comment]
axios中是有cancelToken的，请问luch-request支持吗

**Comment by lei-mu** [comment]
不支持cancelToken。
可以通过`getTask`获取到task。
请求都是异步的，你怎么知道这个请求比另一个慢呢。
可以考虑使用递归。

**Comment by jarrelljiang** [comment]
我想的是每次请求之前先取消这个请求，然后再发起请求

**Comment by lei-mu** [comment]
let task

function get () {
 task.abort()
htpp.get(, {
getTask: (task) => {
task = task
}
})
}

**Comment by jarrelljiang** [comment]
> let requestTask
> 
> function get () {
> requestTask.abort()
> htpp.get(, {
> getTask: (task) => {
> requestTask= task
> }
> })
> }
这样可行，多谢！

**Comment by jarrelljiang** [comment]
> let requestTask
> 
> function get () {
> requestTask.abort()
> htpp.get(, {
> getTask: (task) => {
> requestTask= task
> }
> })
> }

abort()又无效了，这是咋回事啊？之前通过这个方法是可以取消请求的，今天发现又不能取消了。。。

**Comment by lei-mu** [comment]
第一次 requestTask 是unde 你判断了吗？不能取消是什么表现？ err有吗

**Comment by jarrelljiang** [comment]
> 第一次 requestTask 是unde 你判断了吗？不能取消是什么表现？ err有吗

sorry，是我这边的问题。。。
