### ISSUE TITLE
上传多个文件时files参数怎么传？服务器端收到的ContentType为何是text/html

### ISSUE THREAD

**Issue by pcvc** [lei-mu/luch-request#130]
上传多个文件时files参数怎么传？服务器端收到的ContentType为何是text/html？

![微信截图_20230918184748](https://github.com/lei-mu/luch-request/assets/2976517/8005a51f-fc49-44a5-87fe-346503bce484)
![微信截图_20230918184709](https://github.com/lei-mu/luch-request/assets/2976517/550efd5e-c29a-4916-ac93-52195ae23911)

files: [ res.tempFilePaths[0] ]，这样传也不行。还要做其它设置吗？

**Comment by lei-mu** [comment]
哪个端？

files 字段是否按照 [uni.uploadfile](https://uniapp.dcloud.net.cn/api/request/network-file.html#uploadfile) 里的 files参数说明 去传递

**Comment by pcvc** [comment]
H5， files参数说明 => ”files 参数是一个 file 对象的数组“，原来要自己构建此数组。已解决！
