### ISSUE TITLE
关于vue.config.js中transpileDependencies配置问题

### ISSUE THREAD

**Issue by heweiquan** [lei-mu/luch-request#131]
项目使用的是vue3+vite创建：
//https://uniapp.dcloud.net.cn/quickstart-cli.html
`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
![image](https://github.com/lei-mu/luch-request/assets/13057762/a029b066-9358-4aa8-affd-5502229195e7)
vite.config.js文件有差异：
1.在https://vitejs.dev/config官网没有找到transpileDependencies该属性配置。
2.google也没有找到相关资料。
3.感觉不配置这个，项目也能正常使用luch-request。
so，想请问一下这个配置还需要设置吗？
![image](https://github.com/lei-mu/luch-request/assets/13057762/b795259d-bea4-4eac-bb60-0d0fb5167c13)

**Comment by wanglei1020** [comment]
同问

**Comment by lei-mu** [comment]
没问题就不用配置，不会有影响

**Comment by heweiquan** [comment]
好的3Q
