### ISSUE TITLE
http.upload('api/upload/img', ；这个怎么用？method是upload？

### ISSUE THREAD

**Issue by yangxun521** [lei-mu/luch-request#135]
重新问一下
            
  https://www.quanzhan.co/luch-request/guide/3.x/#upload
非常抱歉 我是滚动页面到#upload这里，但是没注意url是#request，让作者产生歧义了。

`export const upl = file => uni.$uv.http.upload('resource/oss/upload', {filePath: file, header: {
  'Content-Type': 'multipart/form-data'
}, custom: {auth: true}})`
![093e25b9e0e3cee95a348d623084e7d](https://github.com/lei-mu/luch-request/assets/74896483/8e923279-315a-4353-a75e-8b76dae7dfba)

然后像正常调用接口调用，下方红框内是可以正常使用的（uni.uploadFile）,但是接口调用报错；上方content-type不需要理会，设置与否都会报这个错
![bf7c5b1760087b7a85c55e0fb83b5cd](https://github.com/lei-mu/luch-request/assets/74896483/b4cc4321-aecf-4b5b-9560-f734abe9f8f0)

![7a733e3bafb46a58ade21ac752745ff](https://github.com/lei-mu/luch-request/assets/74896483/cdae84c1-ff26-4459-bcd6-b823b2330b5c)
两个问题需要请教：
1、如果是参数传的方式不对，应该如何传，我传的是小程序返回的图片临时路径；
2、这个method总是显示upload方式，但是http请求不支持这种方式的；
有没有示例可以参考一下啊？问了很多人，基本没人用这种方式，只能请教作者大佬了，还请不吝赐教！！

_Originally posted by @yangxun521 in https://github.com/lei-mu/luch-request/issues/134#issuecomment-1816028745_

**Comment by FollowZero** [comment]
有人回答一下么？应该是遇到了同样的问题。就是我上传图片的接口 method 需要是 POST

**Comment by lei-mu** [comment]
> 有人回答一下么？应该是遇到了同样的问题。就是我上传图片的接口 method 需要是 POST

![image](https://github.com/lei-mu/luch-request/assets/29419129/830ed735-4a6f-42dd-8236-0257d40e0267)

不要纠结 拦截器 的method 是什么。 只要你调用 uni.upload 方法，它最后一定是 post 方法，content-type multipart。因为uni 为了临时文件路径，底层都已经封装好了。
luch-request 的upload 底层 肯定也是调用uni.upload,参数都基本一样。 你可以直接理解 UPLOAD 就是POST。

**如果上传出现问题，用的luch-request 的upload 方法，后端接口也规定POST 上传，那么问题不在请求类型上，在其他地方找问题**
