### ISSUE TITLE
【BUG】设置请求超时 timeout 没有效果

### ISSUE THREAD

**Issue by 1014156094** [lei-mu/luch-request#139]
![image](https://github.com/lei-mu/luch-request/assets/16074662/f6e1503d-25dd-44b4-9cf9-3b85780498a5)

**Comment by lei-mu** [comment]
[配置超时时间](https://www.quanzhan.co/luch-request/issue/#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E8%B6%85%E6%97%B6%E6%97%B6%E9%97%B4)

是不是没改 networkTimeout request 的时间

**Comment by 1014156094** [comment]
> [配置超时时间](https://www.quanzhan.co/luch-request/issue/#%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE%E8%B6%85%E6%97%B6%E6%97%B6%E9%97%B4)
> 
> 是不是没改 networkTimeout request 的时间

改了一样没效果

**Comment by lei-mu** [comment]
哪个端？
没效果是什么意思？没到180min 就超时了？ 问题描述详细具体
时间配短一点，比如30  ms,试试生效吗

**Comment by 1014156094** [comment]
H5端，一到1分钟就超时了

**Comment by lei-mu** [comment]
经测试无法复现，需要提供可复现的demo。
后端有设置超时时间吗？
