### ISSUE TITLE
字节小程序支持timeout，为啥这边处理判断里面没有字节 然后字节新增js数据预取功能，新增字段id和usePrefetchCache，是否计划加入根对象，目前只能打补丁才能添加吗

### ISSUE THREAD

**Issue by 2548085610** [lei-mu/luch-request#141]
字节小程序支持timeout，为啥这边处理判断里面没有字节
然后字节新增js数据预取功能，新增字段id和usePrefetchCache，是否计划加入根对象，目前只能打补丁才能添加吗

**Comment by lei-mu** [comment]
timeout 没有是因为，插件底层是uni,uni 的[文档](https://uniapp.dcloud.net.cn/api/request/request.html#request)上没有说明支持。这个后续大版本可能会尝试插件放开条件编译...

[数据预取](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/guide/experience-optimization/list/data-preload-js-example),这个建议直接条件编译 + 抖音小程序api 去弄吧
