### ISSUE TITLE
请求超时后我拿到了error中的config，怎么重新发起请求呢？

### ISSUE THREAD

**Issue by tryhank** [lei-mu/luch-request#16]

**Comment by tryhank** [comment]
instance.request(error.config)

**Comment by lei-mu** [comment]
正确答案：instance.middleware(error.config)
[middleware](https://www.quanzhan.co/luch-request/guide/3.x/#middleware)
request 里不包含upload、download,middleware是所有请求方式的超集。包含UPLOAD、DOWNLOAD方法

**Comment by tryhank** [comment]
好的，感谢指导




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lei-mu/luch-request"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 上午10:25
收件人:&nbsp;"lei-mu/luch-request"<luch-request@noreply.github.com&gt;;
抄送:&nbsp;"神龙摆尾"<742721238@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [lei-mu/luch-request] 请求超时后我拿到了error中的config，怎么重新发起请求呢？ (#16)





 
正确答案：instance.middleware(error.config)
 middleware
 request 里不包含upload、download,middleware是所有请求方式的超集。包含UPLOAD、DOWNLOAD方法
