### ISSUE TITLE
请指教，关于file文件上传问题

### ISSUE THREAD

**Issue by nongzhenli** [lei-mu/luch-request#17]
已知文档处写明：**`data支持的文件类型只有Object/String/ArrayBuffer</code>这个真跟我没啥关系 0.0`**

# 场景需求：
上传多图片file[]后端这样子接收，一般都会这么操作哇，先说一般情况下~（且携带其他信息，一同formData提交）
# 操作 ：**（H5端下测试）**
尝试使用post请求，JSON对象作为data参数，设置header **Content-type: ''application/x-www-form-urlencoded; charset=UTF-8"**
成功上传格式 **FormData，**
# 问题：

- file无法无法实现多个 file[]...
- file 变成 **[obejct File], [obejct File] ...** （应该是(binary) 才是的捏）

请问作者，如何去实现可上传FormData参数呢？(这个问题我看下源码，不知道是从那部开始做转换的呢)
![image](https://user-images.githubusercontent.com/19389294/98717622-44d25b00-23c8-11eb-9aa1-628238caa866.png)

**Comment by lei-mu** [comment]
这个问题可以加QQ详细沟通一下；`370306150`
具体可以分几个场景；
1. formData 传参。没有file 文件。  置header Content-type: ''application/x-www-form-urlencoded; charset=UTF-8"
成功上传格式 FormData
2. formData 传参。 有file 文件。 这时候就要用luch-request 里的`upload` [方法（等同于uni的uni.uploadFile(OBJECT)）。[uni.uploadFile(OBJECT)](https://uniapp.dcloud.net.cn/api/request/network-file?id=uploadfile)。
多file 同时上传。使用`files`参数。其他formData 参数，使用`formData`这个参数

**Comment by nongzhenli** [comment]
> 这个问题可以加QQ详细沟通一下；`370306150`
> 具体可以分几个场景；
> 1. formData 传参。没有file 文件。  置header Content-type: ''application/x-www-form-urlencoded; charset=UTF-8"
> 成功上传格式 FormData
> 2. formData 传参。 有file 文件。 这时候就要用luch-request 里的`upload` [方法（等同于uni的uni.uploadFile(OBJECT)）。[uni.uploadFile(OBJECT)](https://uniapp.dcloud.net.cn/api/request/network-file?id=uploadfile)。
> 多file 同时上传。使用`files`参数。其他formData 参数，使用`formData`这个参数
> 

好的，今晚试试~感谢
```
