### ISSUE TITLE
在安卓6.0 webview 中加载uniapp h5网页，使用了该插件，报错。

### ISSUE THREAD

**Issue by aszx-fyh** [lei-mu/luch-request#18]
我是一个用uniapp开发webapp的项目，在ios/android的webview中加载webapp。之前是直接下载源文件到代码里使用，没有问题。然后我看作者更新了，我就 用yarn加载使用，也没有问题。直到最近发现在oppo，红米的一些android 6.0版本的手机上，页面加载不出来。我用安卓调试，发现保错，**unexpected token...**
然后我一步步注释代码，发现import Request from "luch-request"有问题。然后我就试试下载源码，结果可以了，，，很奇怪。
刚开始我还以为是babel没有起作用，es6代码报错。
![QQ拼音截图20201114105344](https://user-images.githubusercontent.com/16113553/99137920-d27fa600-2667-11eb-8b1f-005b4125a281.png)
![QQ拼音截图20201114105239](https://user-images.githubusercontent.com/16113553/99137922-d3183c80-2667-11eb-9e52-55d8a01e7742.png)

**Comment by lei-mu** [comment]
我看你这个用的是 2.x版本。2.x 的最新可用版本是`2.0.1`。 用yarn 或者npm安装的时候注意加入版本号。
你加我qq。 ‘370306150’.  
你这个是cli 项目吗？ vue.config.js 里那个配置加了吗？ [npm](https://www.quanzhan.co/luch-request/guide/2.x/#npm)

**Comment by aszx-fyh** [comment]
> 我看你这个用的是 2.x版本。2.x 的最新可用版本是`2.0.1`。 用yarn 或者npm安装的时候注意加入版本号。
> 你加我qq。 ‘370306150’.
> 你这个是cli 项目吗？ vue.config.js 里那个配置加了吗？ [npm](https://www.quanzhan.co/luch-request/guide/2.x/#npm)

可以了，，确实要在vue.config.js里加配置，还是第一次用这个，受教了。
