### ISSUE TITLE
h5支持 超时时间设置吗？

### ISSUE THREAD

**Issue by best-fan** [lei-mu/luch-request#21]

**Comment by best-fan** [comment]
![image](https://user-images.githubusercontent.com/18264568/101762054-de9c3d80-3b17-11eb-960d-59402d0f1cb8.png)
我设置的90s 没有效果

**Comment by lei-mu** [comment]
最新版本已经支持。

支持度：[timeout 支持度](https://www.quanzhan.co/luch-request/guide/3.x/#middleware)
