### ISSUE TITLE
upload请求失败

### ISSUE THREAD

**Issue by SuperEnsign** [lei-mu/luch-request#24]
**xxx.vue**
evaluateUploadPhoto({
							filePath: this.imagesData[i],
							name: 'photo',
							header: {
								'token': uni.getStorageSync('token')
							}
						})
**index.js**
export const evaluateUploadPhoto = params => (
	http.upload('/evaluate/upload-photo', params)
)
**mergeConfig.js**插件里有去除content-type
// eslint-disable-next-line no-empty
  if (method === 'DOWNLOAD') {

  } else if (method === 'UPLOAD') {
	  config.method = 'POST'
    delete config.header['content-type']
    delete config.header['Content-Type']
    const uploadKeys = [
      // #ifdef APP-PLUS || H5
      'files',
      // #endif
      // #ifdef MP-ALIPAY
      'fileType',
      // #endif
      // #ifdef H5
      'file',
      // #endif
      'filePath',
      'name',
      'formData',
    ]
    uploadKeys.forEach(prop => {
      if (typeof config2[prop] !== 'undefined') {
        config[prop] = config2[prop]
      }
    })
  }
但是请求头里还是包含了Content-Type
Request Headers
Connection: close
Content-Type: application/json
Date: Wed, 16 Dec 2020 06:34:12 GMT
Server: nginx/1.15.4
Transfer-Encoding: chunked

**Comment by lei-mu** [comment]
config.method = 'POST' 
加这个干吗

**Comment by SuperEnsign** [comment]
谢谢，去掉后就正常了
