### ISSUE TITLE
当 Post 请求 data 为 formData 时报错，请求无法发出

### ISSUE THREAD

**Issue by 1014156094** [lei-mu/luch-request#25]
![image](https://user-images.githubusercontent.com/16074662/102758536-da8cdd00-43ad-11eb-95ad-c51d3ddb2c4c.png)
![image](https://user-images.githubusercontent.com/16074662/102758684-13c54d00-43ae-11eb-82c7-a99c91fdbfc4.png)
![image](https://user-images.githubusercontent.com/16074662/102758729-217ad280-43ae-11eb-9e20-b1974ccd3f52.png)

**Comment by lei-mu** [comment]
[发送formData](https://www.quanzhan.co/luch-request/issue/#_8-发送formdata？)
