### ISSUE TITLE
安卓端支持 超时时间设置吗

### ISSUE THREAD

**Issue by lzsmile** [lei-mu/luch-request#27]
设置了60s 没有效果  希望大佬指点一波！

**Comment by lei-mu** [comment]
全局的使用uni那个配置文件
`https://uniapp.dcloud.io/collocation/manifest?id=networktimeout`
<br>
### 局部
<br>
<code>
 // 返回当前请求的task, options。请勿在此处修改options。非必填


    getTask: (task, options) => {
         // setTimeout(() => {
         //   task.abort()
         // }, 500)
    },
</code>
