### ISSUE TITLE
h5 在请求之后拦截器里，添加一个uni.showToast没效果，但是前后的1和2都能打印，请问如何能添加提示？

### ISSUE THREAD

**Issue by chen3728060** [lei-mu/luch-request#28]
/* 请求之后拦截器。可以使用async await 做异步操作  */
http.interceptors.response.use(async (response) => {
        console.log(1)
	uni.showToast({
		icon: 'none',
		title: '测试'
	})
        console.log(2)
剩下都是原来的代码

1和2都能打印，如果放alert也能弹窗，但是放showToast就没任何效果，也不报错，请问如何解决

**Comment by lei-mu** [comment]
是不是和页面里的showToast 冲突了，toast 只能同时显示一个。

加个setTimeout 试试
