### ISSUE TITLE
Cannot read property 'baseURL' of undefined

### ISSUE THREAD

**Issue by zhangchenna** [lei-mu/luch-request#29]
h5 运行时 提示 Cannot read property 'baseURL' of undefined

**Comment by zhangchenna** [comment]
![image](https://user-images.githubusercontent.com/8108749/109448938-26c95d00-7a82-11eb-878a-88af752c6391.png)
conifng 是undefind

**Comment by zhangchenna** [comment]
@lei-mu

**Comment by lei-mu** [comment]
发一下其他代码片段。setConfig 、拦截器。

**Comment by Strong-Gavin** [comment]
请问解决了吗 我也遇到了

**Comment by zhangchenna** [comment]
> 请问解决了吗 我也遇到了

换axios不就行了

**Comment by lei-mu** [comment]
一般是因为在请求拦截器的时候没有  `return config`
