### ISSUE TITLE
钉钉小程序 图片上传  ios手机 直接奔溃退出小程序  

### ISSUE THREAD

**Issue by ywanhzy** [lei-mu/luch-request#32]
钉钉小程序 图片上传  ios手机 直接奔溃退出小程序  真机调试都无法捕获到错误信息  有人遇到过吗

**Comment by lei-mu** [comment]
建议，可以 使用相同参数  使用 [uni.uploadFile](https://uniapp.dcloud.io/api/request/network-file?id=uploadfile)  试一下。如果仍然崩溃，可以给uni在ask 提bug。或者可以更换上传方案试试。
如果不是uni问题。可以加我的qq,详细沟通 `370306150`

**Comment by ywanhzy** [comment]
使用uni.uploadFile 和钉钉的dd.uploadFile上传都没有问题

**Comment by zhangdaba** [comment]
希望执行完后，可以再次修改一下全局的baseURL 地址，想请教一下 ，有这种方式么
