### ISSUE TITLE
App端支持设置responseType

### ISSUE THREAD

**Issue by Qinruiy** [lei-mu/luch-request#35]
https://github.com/dcloudio/uni-app/blob/85b41acd9153cc5022e1bab2b331a3be06a98276/src/platforms/app-plus/service/api/network/request.js#L92-L103

参照uni官方更新

**Comment by lei-mu** [comment]
已给uni docs 提交pr。等待官方回复

**Comment by lei-mu** [comment]
v3.0.6 已更新
