### ISSUE TITLE
拦截器和 TypeScript

### ISSUE THREAD

**Issue by ModyQyW** [lei-mu/luch-request#43]
当前在同时使用 TypeScript 和拦截器时，会遇到类似于 https://github.com/axios/axios/issues/1510 的问题，官方添加了额外的范型解决，参考 <https://github.com/axios/axios/issues/1510#issuecomment-396894600> 和 [axios/index.d.ts](https://github.com/axios/axios/blob/master/index.d.ts)，是否可以参考着调整一下定义？

如果有需要，我可以抽空提个 PR。:D

**Comment by ModyQyW** [comment]
考虑发个版吗？

**Comment by lei-mu** [comment]
在考虑其他的一些修改，之后会发个版

**Comment by nadirvishun** [comment]
看了下，貌似可以这么用，用法是否准确？
拦截器中返回data：
```ts
http.interceptors.response.use((response) => {
  ... 
  return response.data
})
```
然后：
```ts
//定义: 
interface Result {
    code: number,
    msg: string,
    data: any
}
//发起请求: 
http.post<void, Result>()
//返回结果类型: 
response==>Result
```
或者是
```ts
//定义: 
interface Result<T> {
    code: number,
    msg: string,
    data: T
}
//发起请求: 
http.get<User, Result<User>>()
//返回结果类型: 
response==>Result<User>
```
