### ISSUE TITLE
请求出现”cant  read property 'custom' of undefined“

### ISSUE THREAD

**Issue by hacjy** [lei-mu/luch-request#46]
请求的时候的时不时会提示“cant  read property 'custom' of undefined”。这是什么原因导致的？代码如下：

`
//请求拦截器
http.interceptors.request.use((config) => { // 可使用async await 做异步操作
console.log('request interceptors')
console.log(config)
	const token = getTokenStorage();
	 config.header = {
	    ...config.header,
	    token: ''
	  }
	if (token) {
		config.header.token = 'Bearer ' + token;
	}

	if (config.method === 'POST') {
		config.data = JSON.stringify(config.data);
	}

	if (config.custom.loading) {
		uni.showLoading({title:'加载中...'})
	}
	return config
}, error => {
	if (error.config.custom.loading) {
		uni.hideLoading()
	}
	console.log('request interceptors error')
	console.log(error)
	
	console.log(error)
	ret.code = (error.data==undefined||error.data.status==undefined)?405:error.data.status;
	ret.message = (error.data==undefined||error.data.error==undefined)?error.errMsg:error.data.error;
	return Promise.reject(error)
})
`

**Comment by lei-mu** [comment]
看不出来，看样子 是config 不存在了

提供可复现代码或者qq 联系，展示更多代码片段
