### ISSUE TITLE
响应拦截器中如何取出http的状态码

### ISSUE THREAD

**Issue by gas0324** [lei-mu/luch-request#48]
```
http.interceptors.response.use((response) => {
 /* 对响应成功做点什么 可使用async await 做异步操作*/
  console.log(response)
  return response
}, (response) => { 
  /*  对响应错误做点什么 （statusCode !== 200）*/
  console.log(response)
  //这里怎么取出http的状态码
  return Promise.reject(response)
})

**Comment by lei-mu** [comment]
response.statusCode 就是http 状态码

**Comment by gas0324** [comment]
来信已收到。

**Comment by gas0324** [comment]
@lei-mu 我这边在测试的时候发现，在某些情况下 http的状态码不存在，如下图，在settle.js下debug打印的时候就是undefined
![QQ图片20220105164941](https://user-images.githubusercontent.com/14065807/148188879-5607d07f-e5f2-4788-9b58-94c9faf7cc2c.png)
![QQ图片20220105165103](https://user-images.githubusercontent.com/14065807/148188898-7f90a726-3210-449b-aacc-a1198f3bbd9a.png)
![QQ截图20220105165306](https://user-images.githubusercontent.com/14065807/148188908-acd6bda9-621d-4b3c-8e2b-84d908b8c12c.jpg)

**Comment by lei-mu** [comment]
statusCode 并非必存在，比如跨域的时候，请求直接被浏览器拦截了，并不会有。

**Comment by gas0324** [comment]
> statusCode 并非必存在，比如跨域的时候，请求直接被浏览器拦截了，并不会有。

感谢

**Comment by gas0324** [comment]
> 可以使用 相同参数 利用uni.request 去测试。
> 
> statusCode 是uni 的原参数，并没有做任何处理。
> 
> 或者 确认 你请求失败的原因属于哪种，请求超时 也不会有statusCode

我确认我是在跨域，刚才测试了几个情况，404的时候有状态码，403,503没有
