### ISSUE TITLE
希望增加并发请求的支持

### ISSUE THREAD

**Issue by xiaobaibin** [lei-mu/luch-request#50]
后续版本可以增加像axios.all( )和axios.spread( )这样的并发请求吗？
例如车联网的车辆位置轨迹查询，数据量比较大，单次请求不太合适，用分页多次并发请求，成功后合并结果绘制轨迹。PC端我们采用这种方式实现，效果挺好。

**Comment by lei-mu** [comment]
axios.all 等同于 Promise.all ，没有区别，只是axios 换了个名字而已，源码就是返回的Promise.all

区别是 axios.spread 这个方法，让Promise.all 取参方法不一样了。
```` js
axios.all([searchTopic(), searchs()])
  .then(axios.spread(function (allSearchTopic, allSearchs) {
    debugger//打印可以拿到所有的返回值
    allSearchTopic == 方法一的返回值
    allSearchs == 方法二的返回值
  }));
````
之前考虑到区别不大，所以没有增加这个api

解决方案：直接使用[Promise.all](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)
