### ISSUE TITLE
选择多文件进行上传，报错

### ISSUE THREAD

**Issue by Shikyh** [lei-mu/luch-request#59]
在app使用该插件。选择多文件尝试上传后，直接报错。最后无奈只好单文件循环进行调用上传。
![image](https://user-images.githubusercontent.com/27214224/156517739-e1b4ca71-0f9b-4c9a-87d3-0f59bbb376b6.png)
![image](https://user-images.githubusercontent.com/27214224/156517979-41ede750-dab0-4370-bde3-00850d9c8a01.png)
![image](https://user-images.githubusercontent.com/27214224/156518115-9b52ff92-8380-435f-89f1-8753e687b3bd.png)

**Comment by lei-mu** [comment]
[uni.uploadFile](https://uniapp.dcloud.io/api/request/network-file.html)
可以看下  files参数说明   是否符合
