### ISSUE TITLE
这里导致了 dataType: 'string'。失效。

### ISSUE THREAD

**Issue by 0jinxing** [lei-mu/luch-request#60]
https://github.com/lei-mu/luch-request/blob/d8253baa40533b01e79c20e4d795f3c6839e05e6/src/lib/adapters/index.js#L32

**Comment by 0jinxing** [comment]
项目 需要 bigint 支持。

**Comment by 0jinxing** [comment]
https://www.npmjs.com/package/json-bigint

**Comment by lei-mu** [comment]
目前无解，在axios 里应该会有个response 前置处理器，这个没弄。
可以让后端把大数字int转成字符串返回

**Comment by basedanceopen** [comment]
同楼主，可以同底层uni.request保持一致啊，由使用者选择util是否要对response做json parse
` if (typeof response.data === 'string') { `
这里遇到str，都去做下json parse的原因是？这样处理的话 底层uni.request提供的dataType参数岂不是无意义了

**Comment by lei-mu** [comment]
> 同楼主，可以同底层uni.request保持一致啊，由使用者选择util是否要对response做json parse `if (typeof response.data === 'string') {` 这里遇到str，都去做下json parse的原因是？这样处理的话 底层uni.request提供的dataType参数岂不是无意义了

这样做其中的一个原因就是对uni.uploadFile 返回的 JSON 字符串进行处理。

后期这块处理方式 有重构计划

**Comment by hanyucd** [comment]
@0jinxing 我也遇到了这个精度丢失问题。

你是在响应拦截器中，使用 json-bigint parse 解析是么？还是在哪里转换?

**Comment by lijin123** [comment]
我也遇到。咋治呢？
