### ISSUE TITLE
luch-request 和 axios 一样换 Vue 版本不影响吧，但是文档写了不支持 Vue3 是想表达什么呢，有点慌

### ISSUE THREAD

**Issue by 1014156094** [lei-mu/luch-request#61]
https://ext.dcloud.net.cn/plugin?id=392
![image](https://user-images.githubusercontent.com/16074662/158141287-5ab04bef-1765-4a7c-9bb0-9fa01cc96bc9.png)
预期结果：Vue 版本是否会影响

**Comment by lei-mu** [comment]
插件市场配置更新延迟，和vue 版本无关，不影响
