### ISSUE TITLE
请问有木有设计删除拦截器的接口

### ISSUE THREAD

**Issue by jkingfirst** [lei-mu/luch-request#67]
目前luch-requrest 是支持创建多个实例和多个拦截器，导致现在的问题，当我在连续请求一个接口多次或者多个接口的时候，多个拦截器同触发，会造成性能内存的浪费，

**Comment by lei-mu** [comment]
没有设计，没有遇到过需要删除的场景。

const R1 = new Request()

const R2 = new Request()

R1 和R2 的拦截器是不共享的。

没有理解你这个删除的场景。可以具体说一说
