### ISSUE TITLE
config 配置 dataType参数值

### ISSUE THREAD

**Issue by hanyucd** [lei-mu/luch-request#69]
**dataType 参数值只能是 json 吗？ 还可以有其他哪些类型？**

<img width="844" alt="image" src="https://user-images.githubusercontent.com/13725830/167330415-867523c2-69bd-4f92-8b6d-a17cc4867454.png">

我主要是想解决： 后端接口返回订单号出现订单号精度丢失的情况。

dataType 默认是 json，执行了 JSON.parse()。导致 长数字类型精度丢失。

在 Axios 中会有个 transformResponse，可以解决这个问题，在 luch-request 中有没有这个东西？
参考文档： https://blog.51cto.com/u_15585699/5192081

<img width="625" alt="image" src="https://user-images.githubusercontent.com/13725830/167331256-0ef18502-6d16-44e9-85a1-9b5ddc4cd48e.png">

**Comment by hanyucd** [comment]
我主要是想解决： 后端接口返回订单号出现订单号精度丢失的情况。

dataType 默认是 json，执行了 JSON.parse()。导致 长数字类型精度丢失。

在 Axios 中会有个 transformResponse，可以解决这个问题，在 luch-request 中有没有这个东西？

<img width="625" alt="image" src="https://user-images.githubusercontent.com/13725830/167331256-0ef18502-6d16-44e9-85a1-9b5ddc4cd48e.png">

**Comment by lei-mu** [comment]
精度丢失这个问题我也很头疼，这个目前没有设计这个api,只能让后端 转成字符串。

临时解决方案：
或者改一下源码，把源码里对 response 的 JSON.parse 代码注释，等待后续版本支持。

![image](https://user-images.githubusercontent.com/29419129/167333127-7afa4b80-66b0-49b1-ada1-cad2b39cc24b.png)

或者你可以试试（我没有试过）：
你把你精度丢失那个请求的dataType 设置成null试试，我没有试过。

**Comment by hanyucd** [comment]
@lei-mu 我试过了，还是没用。在 axios 中有个 transformResponse，luch-request 中有类似的没？
<img width="397" alt="image" src="https://user-images.githubusercontent.com/13725830/167333791-a9bace00-6af0-44b4-bc91-13c425ed6dbb.png">

<img width="631" alt="image" src="https://user-images.githubusercontent.com/13725830/167333763-043be5a4-6f42-44a7-8cc8-e04215e9a7f1.png">

**Comment by hanyucd** [comment]
@lei-mu 改源码的话注释JSON.parse ，主要我项目是 vue-cli 脚手架搭建的项目，npm install 的 luch-request。每次都要修改源码了。

**Comment by lei-mu** [comment]
![image](https://user-images.githubusercontent.com/29419129/167334946-c29ba85e-5b3a-4886-9c16-7c9156d4f623.png)

**Comment by hanyucd** [comment]
@lei-mu 
哥，你有比较完美的解决方案的时候，说声哈。
