### ISSUE TITLE
简单的一个请求报错，bug 么?

### ISSUE THREAD

**Issue by 1014156094** [lei-mu/luch-request#7]
![image](https://user-images.githubusercontent.com/16074662/89507373-fe84c300-d7fe-11ea-848a-49f5c92d7f58.png)
![image](https://user-images.githubusercontent.com/16074662/89507387-05133a80-d7ff-11ea-859c-9bdf6c94c653.png)
![image](https://user-images.githubusercontent.com/16074662/89507552-3e4baa80-d7ff-11ea-8fd9-5d4b6200d400.png)
![image](https://user-images.githubusercontent.com/16074662/89507438-16f4dd80-d7ff-11ea-9515-2ffa45dce40a.png)

**Comment by lei-mu** [comment]
**错误已解决**
报错原因：
1. 错误的manifest.json 配置
2. 未使用.catch 捕获promise 的错误
