### ISSUE TITLE
希望增加Vue3版本的uniapp的支持

### ISSUE THREAD

**Issue by cuiwenyuan** [lei-mu/luch-request#71]
特别是H5应用和微信小程序

**Comment by lei-mu** [comment]
你说的支持具体指什么？

插件不依赖vue 的，和vue 版本无关。

区别在你们使用时的差异

**Comment by cuiwenyuan** [comment]
看到插件市场上的介绍，不支持Vue3，我还以为不支持呢。


文档方面能介绍下吗？针对Vue3的使用出个简单的介绍。


新手级别的需求，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月25日(星期三) 中午11:26
收件人: ***@***.***&gt;; 
抄送: "崔文远 Troy Cui @***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lei-mu/luch-request] 希望增加Vue3版本的uniapp的支持 (Issue #71)





 
你说的支持具体指什么？
 
插件不依赖vue 的，和vue 版本无关。
 
区别在你们使用时的差异
