### ISSUE TITLE
堵塞界面进行渲染, 无法出现 showToast 或其他洁面动作

### ISSUE THREAD

**Issue by shichenda** [lei-mu/luch-request#75]
请求发出时,未收到返回前, 其他一切动作皆堵塞状态 console 除外.
this.messageShow = true;
try {
let {page,size,where,current} = this;
getMyGoodsList({page,size,where,type:current}).then((res)=>{
this.messageShow = false;
if (res && res.code == 1) {
	const { data } = res;
	this.goodsList = [...this.goodsList,...data];
	if(data.length==size){
		this.loadmore = 'loadmore';
	}else{
		this.loadmore = "nomore";
	}
} else {
	this.$refs.uToast.show({message: res.msg,type: 'error'});
}
});
console.log(222);

如上代码 messageShow 是其他组件显示隐藏的属性, 正常情况是先显示界面, 然后发出请求,请求返回界面隐藏. 但是显示隐藏的动作是被堵塞了, 请求返回数据后才闪出了一下页面.

**Comment by lei-mu** [comment]
messageShow  相当于控制了一个loading 元素。
本意是先显示loading 元素，接口请求成功后在隐藏。

你试试 在请求成功后 
````` 
setTimeout(() => {
this.messageShow = false
}, 1000)
`````
如果表现正常，就是接口请求很快，有闪屏。

或者尝试将上面的代码，放到`this.goodsList = [...this.goodsList,...data];` 之后，现有数据，再显示
