### ISSUE TITLE
获取文件上传进度问题

### ISSUE THREAD

**Issue by li1753846989** [lei-mu/luch-request#76]
环境: 
h5端
chrome版本  102.0.5005.63
luch-request版本 3.0.7
问题描述: 
在上传方法中getTask里使用Update与onProgressUpdate都无法获取上传进度
1. 使用uni插件市场示例中的Update方法,报错Update不是一个方法
2. 使用task.onProgressUpdate也没有调用此方法

请求代码: 
```
// 上传图片
export const uploadImgApi = filePath => {
	return request.upload("/cent-data-core/upload/img", {
		filePath: filePath, // 要上传文件资源的路径。
		name: 'file',
		complete: () => {}, // 此参数是否设置结果一样
		getTask: (task, options) => {
			// task.Update()
			console.log("进入task");
			task.onProgressUpdate((res) => {
				console.log("我进来监听了")
				console.log('上传进度' + res.progress);
				console.log('已经上传的数据长度' + res.totalBytesSent);
				console.log('预期需要上传的数据总长度' + res.totalBytesExpectedToSend);
				// // 测试条件，取消上传任务。
				if (res.progress > 50) {
					task.abort();
				}
			});
		}
	})
}
```
相关截图: 
Update方法报错
![image](https://user-images.githubusercontent.com/50787560/172794097-66da0d20-0992-4f01-bf1d-a519b15570f2.png)

没进入监听方法
![image](https://user-images.githubusercontent.com/50787560/172793179-2674a2e9-0c9e-4d09-a032-16903082cbdd.png)
请求已执行
![image](https://user-images.githubusercontent.com/50787560/172793362-f58b1699-df7a-4e9e-8a3a-d7639ddc2bf0.png)

**Comment by li1753846989** [comment]
@lei-mu 还需要补充什么信息吗

**Comment by lei-mu** [comment]
加我qq:370306150
