### ISSUE TITLE
uniapp微信小程序荣耀V20使用此插件无法请求/直接错误/原生request方法可用

### ISSUE THREAD

**Issue by excxapp** [lei-mu/luch-request#78]
如题：荣耀V20使用此插件无法访问网络。但是原生小程序的request方式是可以。

**Comment by lei-mu** [comment]
没有这个机型，如果你有测试机型。可直接将引入方式暂时改成 js_sdk,然后在源码进行log,看最后的参数是否符合预期。

`/lib/adapters/index.js` 下， 大概93行，将`{..._config,...mergeKeys(optionalKeys, config)}` 打印出来，看是否符合预期参数。

**Comment by excxapp** [comment]
request:fail -118:net::ERR_CONNECTION_TIMED_OUT

客户手机反应是这个错误。
但是uni.request倒是可以，不知道为啥

**Comment by excxapp** [comment]
![image](https://user-images.githubusercontent.com/4355581/174108965-bbdddebd-6481-4dcc-b5d2-8412b94e13c7.png)
