### ISSUE TITLE
取消发送请求

### ISSUE THREAD

**Issue by Taotaopersonal** [lei-mu/luch-request#83]
1.怎么取消一个请求的发送？ 
2.http势力上是否有对应的取消请求发送的构造函数？

**Comment by Taotaopersonal** [comment]
getTask: (task, options) => {
         // 相当于设置超时时间500ms
         // setTimeout(() => {
         //   task.abort()
         // }, 500)
    },

**Comment by lei-mu** [comment]
现在是可以有这个功能，但是不够优雅，后期会对这块的设计修改一下。

```` js
let task = null
http.post('url', {}, {
getTask (task) {
task = task
}
})
setTimeout(() => {
 task&&task.abort()
 }, 500)
````
