### ISSUE TITLE
dataType设置成string，返回数据还是json

### ISSUE THREAD

**Issue by zhanleibo** [lei-mu/luch-request#87]
// 请求拦截
uni.$u.http.interceptors.request.use((config) => { 
		config.data = config.data || {}
		config.dataType = 'string'
		return config
	}, config => { // 可使用async await 做异步操作
		return Promise.reject(config)
	})

	// 响应拦截
	uni.$u.http.interceptors.response.use((response) => {
		console.log(response); 
		return response.data
	}, (response) => {
		return Promise.reject(response)
	})

dataType设置成string后，在响应拦截中还是json

**Comment by lei-mu** [comment]
responseType
