### ISSUE TITLE
interceptors.response.use 参数内的header有丢失

### ISSUE THREAD

**Issue by ukhack** [lei-mu/luch-request#88]
实际有10个header，包含set-token,Date等在内。

拿到的只有一个Content-Type:application/json; charset=utf-8

**Comment by lei-mu** [comment]
响应头吗？

直接用uni.request 试下

响应头直接用的 uni.request 返回的头

**Comment by ukhack** [comment]
昨天又查了一遍资料。
这个是xhr规范不允许获取其他header。uni-request遵循了这个规范。
